---
title: "Data Visualisation"
format: pdf
editor: visual
---


```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(readr)
library(ggplot2)
theme_set(theme_bw())
library(tidyr)

library(signal)

conflicted::conflicts_prefer(dplyr::filter, dplyr::select)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r importation data}
#| 
data_NIRS_raw <- read_csv2("data/NIRS_data/Full_dataset.csv")
fun_convert_num = function(x){
  x = stringr::str_replace(x, ',', '.' )
  return(as.numeric(x))
}


# Set data (transform wavelength in number and so on)
data_NIRS <- data_NIRS_raw %>% 
  select(Sample_ID, Accession, `N regime`, `W regime`, Tissue, `12489,6`:`3594,9`) %>% 
  pivot_longer(-c(Sample_ID:Tissue), names_to = "Wavenumber",
               values_to = "Absorbance", 
               names_transform = fun_convert_num)%>% 
  arrange(Sample_ID, Wavenumber) %>% 
  mutate(Absorbance_SNV = (Absorbance - mean(Absorbance))/sd(Absorbance), .by = Sample_ID)  %>% 
  mutate(Absorbance_SG_0 = sgolayfilt(Absorbance_SNV, p = 3)) %>% 
  mutate(Absorbance_SG_1 = sgolayfilt(Absorbance_SNV, p = 3, m = 1)) 

data_NIRS$Sample_ID <- as.factor(data_NIRS$Sample_ID)
data_NIRS$Accession <- as.factor(data_NIRS$Accession)
data_NIRS$`N regime` <- as.factor(data_NIRS$`N regime`)
data_NIRS$`W regime` <- as.factor(data_NIRS$`W regime`)
data_NIRS$Tissue <- as.factor(data_NIRS$Tissue)

# subsample to make plots quicker
id_train = data_NIRS %>% 
  distinct(Sample_ID, Accession, `N regime`, `W regime`, Tissue ) %>% 
  slice_sample(prop = .1, by = c(Accession, `N regime`, `W regime`, Tissue) ) %>% 
  select(Sample_ID)


data_plot = data_NIRS %>% 
  inner_join(id_train)

# création d'un vecteur des différentes longueur d'ondes.
wavelength <- data_NIRS %>% filter(Sample_ID == "15_N1S1_03-19_Res_1") %>% arrange(-Wavenumber) %>%  select(Wavenumber) %>% as.matrix() %>% as.vector()
```


## Missing data

```{r missing data}
sum(is.na(data_NIRS_raw))
# Aucune données manquante
```

## Data repartition

```{r data repartition}
require(ggplot2)
require(cowplot)

#Barplot nu nombre d'observations pour les modalité des variables qualitatives

#Création de la fonction "eq" pour faire les barplots
eq <- function(x) {
  data_NIRS_raw  |> 
    ggplot() + aes(x = x) +
    geom_bar(fill = "darkolivegreen3") + 
    labs(y = "Nombre")+
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(), #Suppression de la grille majeure
          panel.grid.minor = element_blank(), #suppression de la grille mineure
          panel.border = element_blank(), #suppression du cadre
          panel.background = element_blank(), #suppression du fond
          text = element_text(size = 12),#augmentation de la taille des labels
          axis.title.x=element_blank(),#suppression du titre des x
          axis.ticks.x=element_blank())#suppression des x ticks
}

#Barplot des différentes variables qualitatives
plot1 <- eq(data_NIRS_raw$`Growth season`)
plot1 <- plot1 + theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot2 <- eq(data_NIRS_raw$`Growth condition`)
plot3 <- eq(data_NIRS_raw$`N regime`)
plot4 <- eq(data_NIRS_raw$`W regime`)
plot5 <- eq(data_NIRS_raw$`Tissue`)
plot5 <- plot5 + theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Création d'un panneau avec les barplots
#Création d'une première ligne de barplots alignés
top_row <- plot_grid(plot1, plot2, plot3, align = "h", axis = "l", ncol = 3)
#Création d'une seconde ligne de barplots alignés
bottom_row <- plot_grid(plot4, plot5, align = "h", axis = "l", ncol = 3)
#Création du panneau compet contenant les deux lignes de barplots
plot_grid(top_row, bottom_row, ncol = 1)

#Création d'un barplot a part pour la variable "Accession"
plot6 <- eq(data_NIRS_raw$`Accession`)
plot6 <- plot6+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 7))
plot6
```

## Correlation between variable

```{r splines}
# On décide d'approcher la courbe réelle discrétisée via des fonctions splines
library(splines)
snv_x <- t(scale(t(data_NIRS_raw[,-c(1:14)]))) # on recrée une matrice des ondes centrées réduite
# En voulant reprendre les data.frame, déja transformé, j'avais des problèles de classes d'objet... d'ou ce nouveau snv_x

# nombre de splines 
n_splines = 50

B <- bs(wavelength, df = n_splines) # Création des splines
# matplot(wavelength, B, type = "l", col = "blue", lty = 1) # affichage des différentes fonctions

mod <- lm(x ~., data = data.frame(x = snv_x[1,], B)) # modèle linéaire entre la première courbe et les splines

alpha <- coef(mod)[-1]
spl <- B%*% alpha + coef(mod)[1] # création de la nouvelle courbe
plot(wavelength, snv_x[1,], type = "l", col = "blue")
lines(wavelength, spl, col = "red")
```
