---
title: "Graines"
format: html
editor: visual
---
Librairies
```{r}
library(refund)
library(pls)
library(FactoMineR)
library(VIM)
library(naniar)
```


```{r}
#Changement des noms de colonnes de variety vers Genotype dans pheno
pheno <- pheno |>    
  rename(Genotype = variety)  

#Fusion des jeux de données pheno et graines_MEAN pour crée NIRS_pheno_g
NIRS_pheno_g <- graines_MEAN |>    
  left_join(pheno)

#Visualisation de potentielles NA
#matrixplot(NIRS_pheno_g)

#Comptage de potentielles NA
#print(n_miss(NIRS_pheno_g))

#Suppression des lignes contenant des NA
NIRS_pheno_g <- drop_na(NIRS_pheno_g)
```

```{r}
fun_model <- function(X, Y, Kx = 50, nfold = 10) {
  
  #Création des segments
  segments <- cvsegments(length(Y), nfold)
  
  ### Modèle nul ###
  #Création d'un vecteur pour le receuil des valeurs prédites
  cvpred_nul <- numeric(length(Y))
  for (k in 1:nfold) {
    #Indices des observations pour l'ajustement (observations hors du segment k)
    train_id <- setdiff(seq_len(length(Y)), segments[[k]])
    #Indices des observations pour la prédiction (observations du segment k)
    test_id  <- segments[[k]]
    # Création du modèle nul qui est la moyenne de l'échantillon train
    y_mean <- mean(Y[train_id])
    # Prédiction sur l'échantillon test qui est donc la moyenne de l'échantillon train
    cvpred_nul[test_id] <- y_mean
  }
  
  #PRESS du modèle nul
  PRESS_nul <- sum((Y - cvpred_nul)^2)
  #MSEP du modèle nul
  MSEP_nul <- mean((Y - cvpred_nul)^2)
  #RMSEP du modèle nul
  RMSEP_nul <- sqrt(MSEP_nul)
  
  ### Model fonctionnel ###
  #création d'un vecteur qui contiendra les valeurs prédites
  cvpred = numeric(length(Y))
  #On ajuste le modèle sur tous les segments sauf le kième 
  for (k in 1:nfold) {
    #Indices des observations pour l'ajustement (observations hors du segment k)
    train_id <- setdiff(seq_len(length(Y)), segments[[k]])
    #Indices des observations pour la prédiction (observations du segment k)
    test_id  <- segments[[k]]
    #Ajustement du modèle sur l'echantillon train
    fd_mod <- pfr(
      Y ~ lf(X, k = Kx, bs = "ps"),
      data = list(
        Y = Y[train_id],
        X = X[train_id, ]
      )
    )
    #prédiction sur l'échantillon test
    cvpred[test_id] <- predict(
      fd_mod,
      newdata = list(X = X[test_id, ])
    )
  }
  
  #PRESS
  PRESS <- sum((Y-cvpred)^2)
  #MSEP
  MSEP <- mean((Y-cvpred)^2)
  #RMSEP
  RMSEP <- sqrt(MSEP)
  
  ### Gain relative en % ###
  err_relative <- (MSEP_nul - MSEP)/MSEP_nul*100
  err_relative <- round(err_relative, 2)
  
  #Appel des sorties
  #Liste contenant les résultats
  result <- list()
  #Appel du gain avec $err_relative
  result$err_relative <- err_relative
  #Appel de la MSEP avec $MSEP
  result$MSEP <- round(MSEP, 2)
  #Appel de la régression fonctionnelle en sortie de fonction avec $model_fun_out
  result$model_fun_out <- fd_mod
  #Appel des résidus des régressions avec $model_fun_residus
  residus_vc <- Y - cvpred
  result$model_fun_residus <- residus_vc
  #Appel des prédictions avec $pred_fun_out
  result$pred_fun_out <- cvpred
  return(result)
}
```

Extraction des spectres (X) et des phénotypes (Y)
```{r}
#Extraction des colonnes contenants les spectres
X <- as.matrix(NIRS_pheno_g[, 2:1949])

#Indices des colonnes pour lesquells le modèle sera ajusté
Y_cols <- 1950:1972
```

Métriques pour tous les traits phénotypiques
```{r}
#Ajustement du modèle pour tous les phénotypes
res_metrics_g <- lapply(Y_cols, function(i) {
  Y <- NIRS_pheno_g[[i]]
  res_fd_mod <- fun_model(X, Y)
  data.frame(Gain = res_fd_mod$err_relative, 
             MSEP = res_fd_mod$MSEP,
             row.names = colnames(NIRS_pheno_g[i]))
})

#Simplification du data.frame avec les métriques en colonnes et les traits phénotypiques en ligne
res_metrics_g <- do.call(rbind, res_metrics_g)
```

Analyse des résidus
```{r}
#Extraction d'un tableau contenant les résidus pour chaque phénotypes
res_resid <- lapply(Y_cols, function(i) {
  Y <- NIRS_pheno_g[[i]]
  res_resid <- fun_model(X, Y)
  residus <- res_resid$model_fun_residus
})

table_residus <- as.data.frame(do.call(cbind, res_resid))
colnames(table_residus) <- colnames(NIRS_pheno_g)[Y_cols]
table_residus <- cbind(NIRS_pheno_g[1], table_residus)

#Extraction d'un tabelau contenant les prédictions pour chaque phénotypes
res_pred <- lapply(Y_cols, function(i) {
  Y <- NIRS_pheno_g[[i]]
  res_pred <- fun_model(X, Y)
  pred <- res_pred$pred_fun_out
})

table_pred <- as.data.frame(do.call(cbind, res_pred))
colnames(table_pred) <- colnames(NIRS_pheno_g)[Y_cols]
table_pred <- cbind(NIRS_pheno_g[1], table_pred)

#Représentation graphique résidus en fonction des prédictions
plot_fun <- function(var) {
  var_name <- deparse(substitute(var))
  plot(table_pred[[var_name]], 
       table_residus[[var_name]],
       pch = 21,
       bg = "red",
       col = "black",
       xlab = "Prédiction après VC",
       ylab = "Résidus")
}

plot_fun(RDW)

#ACP
#ACP_res <- PCA(table_residus[c(-1)])
```

Extraction des fonctions $\beta$
```{r}
#Graphique de la fonction des beta
res_model <- lapply(Y_cols, function(i) {
  Y <- NIRS_pheno_g[[i]]
  res_model <- fun_model(X, Y)
  model <- res_model$model_fun_out
})

names(res_model) <- colnames(NIRS_pheno_g[Y_cols])

#Représentation graphique des fonctions des beta
bhat.lf <- coef(res_model[["SR"]], n=100)
bhat.lf$upper <- bhat.lf$value + 1.96*bhat.lf$se
bhat.lf$lower <- bhat.lf$value - 1.96*bhat.lf$se
fda::matplot(bhat.lf$X.argvals, bhat.lf[,c(2, 4, 5)], 
        type = "l",
        ylab=expression(paste(beta(t))), xlab="t")
```

